#!bin/bash

for (( x=0; x <= 570; x+=10 )) 

do
   cp GetTc -t ${x}
   cp GetPlot -t ${x}
   cp GetResults -t ${x}
   cp GetDiagram -t ${x}
   cp -r PlotPack -t ${x}
   cd ${x} 
   rm -rf Output.dat *png
   bash GetPlot
   #bash GetDiagram 
   cd ..
done
